### ISSUE TITLE
Fall damage

### ISSUE THREAD

**Issue by Hakhaktak** [derpfacedirk/Goldiriath#30] opened 2015-08-30 18:38 UTC
Do we want people to fall 10 blocks, drink a health potion, and then start rekking everyone? Will people with light armor have less fall damage than people with heavy armor? Will the damage increase be exponential or linear?

**Comment by JeromSar** [comment] 2015-08-30 19:04
Duplicate of https://github.com/Goldiriath/Goldiriath/issues/27?

**Comment by Hakhaktak** [comment] 2015-08-30 19:06
Not really, it's of course implemented in the health system, but this is more specific on the fall damage it self rather than how the health system in general will be. How will fall damage occur, are there different kinds of fall damage.

**Comment by JeromSar** [comment] 2015-08-30 19:13
We decided something along the lines of:
- Jumping from a 8 block jump or higher will kill you.
- You survive from a shorter fall, but you'll get Slowness II to 10-20 seconds.

**Comment by JeromSar** [comment] 2016-02-11 09:01
Due to limitations, we've agreed to the following:
- You receive the the usual amount of hearts damage as you would in vanilla minecraft.
- The remaining health is reflected in Goldiriath's health.

**Comment by JeromSar** [comment] 2016-02-11 09:02
Implemented in https://github.com/Goldiriath/Goldiriath/commit/8a1d164b313530bec60ba774487277bb16a4dbe2

**Comment by JeromSar** [comment] 2017-07-31 14:12
Still partially broken, reopening.

**Comment by JeromSar** [comment] 2017-07-31 20:06
Superseded by #57

**Closed as completed by JeromSar** 2017-07-31 20:06 UTC
Labels: Feature
